"""
Procurement data extracted from Purchase Order List.
Suppliers, orders, and line items sourced from the provided PO List image.
"""

import pandas as pd
import numpy as np

def get_purchase_orders():
    """Returns the main purchase orders dataframe."""
    orders = [
        # Order 51681 - BASINI AVOCADO ETC LIMITED
        {
            "order_id": "51681",
            "po_number": "PO-BA-001782",
            "supplier_code": "SUPP-001782",
            "supplier_name": "BASINI AVOCADO ETC LIMITED",
            "category": "Agricultural Produce",
            "currency": "EUR",
            "order_date": "2024-01-05",
            "delivery_date": "2024-01-20",
            "status": "Received",
            "quantity": 5000,
            "unit_price": 1.85,
            "amount": 9250.00,
            "received_qty": 5000,
            "invoiced": "Yes",
        },
        # Order 50761 - BASINI (K) LIMITED
        {
            "order_id": "50761",
            "po_number": "PO-CM-000904",
            "supplier_code": "CM000904",
            "supplier_name": "BASINI (K) LIMITED",
            "category": "Trading",
            "currency": "KES",
            "order_date": "2024-01-08",
            "delivery_date": "2024-01-25",
            "status": "Received",
            "quantity": 120,
            "unit_price": 8500.00,
            "amount": 1020000.00,
            "received_qty": 120,
            "invoiced": "Yes",
        },
        # JILAPRICA KENYA LIMITED via CAPCO TRADING
        {
            "order_id": "50762",
            "po_number": "PO-JK-000711",
            "supplier_code": "SUPP-000711",
            "supplier_name": "JILAPRICA KENYA LIMITED",
            "category": "Trading - CAPCO",
            "currency": "KES",
            "order_date": "2024-01-10",
            "delivery_date": "2024-01-28",
            "status": "Received",
            "quantity": 300,
            "unit_price": 4500.00,
            "amount": 1350000.00,
            "received_qty": 300,
            "invoiced": "Yes",
        },
        # ALIMED AGENCIES
        {
            "order_id": "51200",
            "po_number": "PO-CNTR-000312",
            "supplier_code": "CNTR-000312",
            "supplier_name": "ALIMED AGENCIES",
            "category": "Medical Supplies",
            "currency": "KES",
            "order_date": "2024-01-12",
            "delivery_date": "2024-02-01",
            "status": "Received",
            "quantity": 50,
            "unit_price": 12300.00,
            "amount": 615000.00,
            "received_qty": 50,
            "invoiced": "Yes",
        },
        # ALIMED AGENCIES - second line
        {
            "order_id": "51201",
            "po_number": "PO-CNTR-000312-B",
            "supplier_code": "CNTR-000312",
            "supplier_name": "ALIMED AGENCIES",
            "category": "Medical Supplies",
            "currency": "KES",
            "order_date": "2024-01-15",
            "delivery_date": "2024-02-05",
            "status": "Partially Received",
            "quantity": 30,
            "unit_price": 8750.00,
            "amount": 262500.00,
            "received_qty": 20,
            "invoiced": "No",
        },
        # TRACK AND TRACE LIMITED
        {
            "order_id": "51310",
            "po_number": "PO-CNTR-000214",
            "supplier_code": "CNTR-000214",
            "supplier_name": "TRACK AND TRACE LIMITED",
            "category": "IT & Software",
            "currency": "KES",
            "order_date": "2024-01-18",
            "delivery_date": "2024-02-10",
            "status": "Received",
            "quantity": 1,
            "unit_price": 2111000.00,
            "amount": 2111000.00,
            "received_qty": 1,
            "invoiced": "Yes",
        },
        # TRACK AND TRACE LIMITED - second order
        {
            "order_id": "51311",
            "po_number": "PO-CNTR-000214-B",
            "supplier_code": "CNTR-000214",
            "supplier_name": "TRACK AND TRACE LIMITED",
            "category": "IT & Software",
            "currency": "KES",
            "order_date": "2024-02-01",
            "delivery_date": "2024-02-20",
            "status": "Received",
            "quantity": 1,
            "unit_price": 850000.00,
            "amount": 850000.00,
            "received_qty": 1,
            "invoiced": "Yes",
        },
        # REVIVAL SOFTWARE LIMITED
        {
            "order_id": "51420",
            "po_number": "PO-CNTR-000333",
            "supplier_code": "CNTR-000333",
            "supplier_name": "REVIVAL SOFTWARE LIMITED",
            "category": "IT & Software",
            "currency": "KES",
            "order_date": "2024-01-22",
            "delivery_date": "2024-02-15",
            "status": "Received",
            "quantity": 1,
            "unit_price": 135000.00,
            "amount": 135000.00,
            "received_qty": 1,
            "invoiced": "Yes",
        },
        # GATEWAY EXPERTS SERVICES LIMITED
        {
            "order_id": "51500",
            "po_number": "PO-CNTR-000344",
            "supplier_code": "CNTR-000344",
            "supplier_name": "GATEWAY EXPERTS SERVICES LIMITED",
            "category": "Logistics & Clearing",
            "currency": "KES",
            "order_date": "2024-01-25",
            "delivery_date": "2024-02-12",
            "status": "Received",
            "quantity": 3,
            "unit_price": 75000.00,
            "amount": 225000.00,
            "received_qty": 3,
            "invoiced": "Yes",
        },
        # GATEWAY EXPORTS SERVICES LIMITED
        {
            "order_id": "51501",
            "po_number": "PO-CNTR-000346",
            "supplier_code": "CNTR-000346",
            "supplier_name": "GATEWAY EXPORTS SERVICES LIMITED",
            "category": "Logistics & Clearing",
            "currency": "KES",
            "order_date": "2024-01-28",
            "delivery_date": "2024-02-18",
            "status": "Received",
            "quantity": 5,
            "unit_price": 58000.00,
            "amount": 290000.00,
            "received_qty": 5,
            "invoiced": "Yes",
        },
        {
            "order_id": "51502",
            "po_number": "PO-CNTR-000346-B",
            "supplier_code": "CNTR-000346",
            "supplier_name": "GATEWAY EXPORTS SERVICES LIMITED",
            "category": "Logistics & Clearing",
            "currency": "KES",
            "order_date": "2024-02-05",
            "delivery_date": "2024-02-25",
            "status": "Partially Received",
            "quantity": 4,
            "unit_price": 62000.00,
            "amount": 248000.00,
            "received_qty": 2,
            "invoiced": "No",
        },
        {
            "order_id": "51503",
            "po_number": "PO-CNTR-000346-C",
            "supplier_code": "CNTR-000346",
            "supplier_name": "GATEWAY EXPORTS SERVICES LIMITED",
            "category": "Logistics & Clearing",
            "currency": "USD",
            "order_date": "2024-02-10",
            "delivery_date": "2024-03-01",
            "status": "Pending",
            "quantity": 2,
            "unit_price": 1450.00,
            "amount": 2900.00,
            "received_qty": 0,
            "invoiced": "No",
        },
        # POTENCY COMPANY LIMITED
        {
            "order_id": "51600",
            "po_number": "PO-CNTR-000358",
            "supplier_code": "CNTR-000358",
            "supplier_name": "POTENCY COMPANY LIMITED",
            "category": "General Supplies",
            "currency": "KES",
            "order_date": "2024-02-01",
            "delivery_date": "2024-02-20",
            "status": "Received",
            "quantity": 200,
            "unit_price": 1200.00,
            "amount": 240000.00,
            "received_qty": 200,
            "invoiced": "Yes",
        },
        # KENYA BUREAU OF STANDARDS - First contract
        {
            "order_id": "51700",
            "po_number": "PO-CNTR-000368",
            "supplier_code": "CNTR-000368",
            "supplier_name": "KENYA BUREAU OF STANDARDS",
            "category": "Regulatory & Compliance",
            "currency": "KES",
            "order_date": "2024-02-03",
            "delivery_date": "2024-02-28",
            "status": "Received",
            "quantity": 1,
            "unit_price": 320000.00,
            "amount": 320000.00,
            "received_qty": 1,
            "invoiced": "Yes",
        },
        # KENYA BUREAU OF STANDARDS - Second contract
        {
            "order_id": "51701",
            "po_number": "PO-CNTR-000369",
            "supplier_code": "CNTR-000369",
            "supplier_name": "KENYA BUREAU OF STANDARDS",
            "category": "Regulatory & Compliance",
            "currency": "KES",
            "order_date": "2024-02-08",
            "delivery_date": "2024-03-05",
            "status": "Received",
            "quantity": 1,
            "unit_price": 210000.00,
            "amount": 210000.00,
            "received_qty": 1,
            "invoiced": "Yes",
        },
        # WEIGHT FRANK VALUERS LIMITED
        {
            "order_id": "51800",
            "po_number": "PO-CNTR-000370",
            "supplier_code": "CNTR-000370",
            "supplier_name": "WEIGHT FRANK VALUERS LIMITED",
            "category": "Valuation Services",
            "currency": "KES",
            "order_date": "2024-02-12",
            "delivery_date": "2024-03-01",
            "status": "Received",
            "quantity": 2,
            "unit_price": 95000.00,
            "amount": 190000.00,
            "received_qty": 2,
            "invoiced": "Yes",
        },
        # INDUSTRIAL VESSELS INSPECTORS
        {
            "order_id": "51900",
            "po_number": "PO-CNTR-000385-A",
            "supplier_code": "CNTR-000385",
            "supplier_name": "INDUSTRIAL VESSELS INSPECTORS",
            "category": "Inspection Services",
            "currency": "KES",
            "order_date": "2024-02-15",
            "delivery_date": "2024-03-05",
            "status": "Received",
            "quantity": 4,
            "unit_price": 45000.00,
            "amount": 180000.00,
            "received_qty": 4,
            "invoiced": "Yes",
        },
        {
            "order_id": "51901",
            "po_number": "PO-CNTR-000385-B",
            "supplier_code": "CNTR-000385",
            "supplier_name": "INDUSTRIAL VESSELS INSPECTORS",
            "category": "Inspection Services",
            "currency": "KES",
            "order_date": "2024-02-20",
            "delivery_date": "2024-03-10",
            "status": "Partially Received",
            "quantity": 3,
            "unit_price": 45000.00,
            "amount": 135000.00,
            "received_qty": 2,
            "invoiced": "No",
        },
        {
            "order_id": "51902",
            "po_number": "PO-CNTR-000385-C",
            "supplier_code": "CNTR-000385",
            "supplier_name": "INDUSTRIAL VESSELS INSPECTORS",
            "category": "Inspection Services",
            "currency": "KES",
            "order_date": "2024-03-01",
            "delivery_date": "2024-03-20",
            "status": "Pending",
            "quantity": 5,
            "unit_price": 45000.00,
            "amount": 225000.00,
            "received_qty": 0,
            "invoiced": "No",
        },
    ]
    df = pd.DataFrame(orders)
    df["order_date"] = pd.to_datetime(df["order_date"])
    df["delivery_date"] = pd.to_datetime(df["delivery_date"])
    return df


def get_kes_equivalent(df):
    """Convert all amounts to KES equivalent for comparison."""
    fx = {"KES": 1.0, "EUR": 145.0, "USD": 128.0}
    df = df.copy()
    df["amount_kes"] = df.apply(
        lambda r: r["amount"] * fx.get(r["currency"], 1.0), axis=1
    )
    return df


if __name__ == "__main__":
    df = get_purchase_orders()
    df = get_kes_equivalent(df)
    print(df[["order_id", "supplier_name", "amount", "currency", "amount_kes", "status"]].to_string())
    print(f"\nTotal KES Equivalent: {df['amount_kes'].sum():,.2f}")
